//
//  SdaiErrorEvent.swift
//  SwiftSDAIcore
//
//  Created by Yoshida on 2025/08/30.
//  Copyright © 2025 Tsutomu Yoshida, Minokamo, Japan. All rights reserved.
//

import Foundation

extension SDAISessionSchema {

	/// ISO 10303-22 (7.3.2) error_base
	///
	/// An error_base is a selection of an entity_instance or an aggregate _instance and is related to a particular error generated by the SDAI implementation.
	///
	public enum ErrorBase {
		case entityInstance(SDAIParameterDataSchema.EntityInstance)
		case aggregateInstance(SDAIParameterDataSchema.AggregateInstance)
	}

	/// ISO 10303-22 (7.4.6) event
	///
	/// An event is a notation of some occurrence related to an SDAI operation at some moment during a session.
	///
	public class Event: SDAI.Object {
		//MARK: Attribute definitions:
		public let functionID: StaticString
		public let time: TimeStamp

		//MARK: swift language binding
		public init(functionID: StaticString) {
			self.functionID = functionID
			self.time = TimeStamp()
		}

	}//class


	/// ISO 10303-22 (7.4.7) error_event
	///
	/// An error_event is an event generated as result of an SDAI operation that has failed to execute successfully or as the result of the Record error operation.
	///
	public final class ErrorEvent: Event, @unchecked Sendable
	{
		//MARK: Attribute definitions:
		public var error: INTEGER { errorIndicator.errorCode }

		public var description: STRING {
			"\(self.errorIndicator) [\(self.errorIndicator.errorCode)]: \(self.errorIndicator.errorDescription) #\(self.functionID) @\(self.time) \n\(self.detailDescription)"
		}

		public var base: ErrorBase? { errorIndicator.errorBase }

		//MARK: swift language binding
		public let errorIndicator: SDAI.ErrorIndicator
		public let detailDescription: STRING

		internal init(
			errorIndicator: SDAI.ErrorIndicator,
			functionID: StaticString,
			detail: STRING)
		{
			self.errorIndicator = errorIndicator
			self.detailDescription = detail

			super.init(functionID: functionID)
		}//init

	}

}//extension

extension SDAI {
	public static func raiseErrorAndTrap(
		_ error: SDAI.ErrorIndicator,
		detail: SDAISessionSchema.STRING,
		functionID: StaticString=#function ) -> Never
	{
		self.raiseErrorAndContinue(error, detail: detail, functionID: functionID)

		fatalError("SDAI runtime is trapped by the error event.")
	}//func


	public static func raiseErrorAndContinue(
		_ error: SDAI.ErrorIndicator,
		detail: SDAISessionSchema.STRING,
		functionID: StaticString=#function )
	{
		let errorEvent = SDAISessionSchema.ErrorEvent(
			errorIndicator: error, functionID: functionID, detail: detail)

		if let session = SDAISessionSchema.activeSession
		{
			if session.recordingActive {
				session.append(errorEvent: errorEvent)
			}
			session.errorEventCallback?(errorEvent, #isolation)
		}

		loggerSDAI.error("\(errorEvent.description)")
	}//func


	/// ISO 10303-22 (11) SDAI errors
	///
	/// Table 2 - SDAI error indicators
	///
	/// Table 2 specifies a set of standard error indicator constants along with a description of the error and the or code value that shall be set as the error_event.error value when the error occurs. The error indicator constant name is formed by combining a target with a predicate separated by an underscore. For example: MO_NOPN for SDAI-model not open. For the purposes of table 2 and the possible error indicators specified for each operation in clause 10, the following target abbreviations apply.
	///
	/// - AI:	aggregate
	/// - AT:	instance attribute
	/// - ED:	entity definition
	/// - EI:	entity instance
	/// - ER:	event recording
	/// - EX:	expression
	/// - FN:	function
	/// - IR:	iterator
	/// - IX:	index
	/// - OP:	operator
	/// - RP:	repository
	/// - RU:	rule
	/// - SC:	scope
	/// - SD:	schema definition
	/// - SI:	schema instance
	/// - SS:	session
	/// - MO:	SDAI-model
	/// - MX:	SDAI-model access
	/// - TR:	transaction
	/// - SY:	underlying system
	/// - VA:	value
	/// - VT:	value type
	///
	/// For the purposes of table 2 and the possible error indicators specified for each operation in clause 10, the following predicate abbreviations apply.
	///
	/// - DUP :	duplicate
	/// - EAB :	ended abnormally
	/// - ERR :	error
	/// - EXS :	exists
	/// - NAVL:	not available
	/// - NDEF:	not defined
	/// - NDEQ:	not domain equivalent
	/// - NEXP:	not exported
	/// - NEXS:	not exist
	/// - NOPN:	not open
	/// - NRW :	not read-write
	/// - NSET:	not set or empty
	/// - NSUP:	not supported
	/// - NVLD:	invalid
	/// - OPN :	is open
	/// - RO  :	read-only
	/// - RW  :	read-write
	///
	public enum ErrorIndicator: Sendable
	{
		case SS_OPN(SDAISessionSchema.SdaiSession)
		case SS_NAVL
		case SS_NOPN

		case RP_NEXS
		case RP_NAVL(SDAISessionSchema.SdaiRepository)
		case RP_OPN(SDAISessionSchema.SdaiRepository)
		case RP_NOPN(SDAISessionSchema.SdaiRepository)

		case TR_EAB(SDAISessionSchema.SdaiTransaction)
		case TR_EXS(SDAISessionSchema.SdaiTransaction)
		case TR_NAVL(SDAISessionSchema.SdaiTransaction)
		case TR_RW(SDAISessionSchema.SdaiTransaction)
		case TR_NRW(SDAISessionSchema.SdaiTransaction)
		case TR_NEXS

		case MO_NDEQ(SDAIPopulationSchema.SdaiModel)
		case MO_NEXS
		case MO_NVLD(SDAIPopulationSchema.SdaiModel)
		case MO_DUP(SDAIPopulationSchema.SdaiModel)

		case MX_NRW(SDAIPopulationSchema.SdaiModel)
		case MX_NDEF(SDAIPopulationSchema.SdaiModel)
		case MX_RW(SDAIPopulationSchema.SdaiModel)
		case MX_RO(SDAIPopulationSchema.SdaiModel)

		case SD_NDEF

		case ED_NDEF
		case ED_NDEQ
		case ED_NVLD(SDAIDictionarySchema.EntityDefinition)

		case RU_NDEF

		case EX_NSUP(SDAIDictionarySchema.Bound)

		case AT_NVLD(SDAIAttributeType)
		case AT_NDEF

		case SI_DUP(SDAIPopulationSchema.SchemaInstance)
		case SI_NEXS

		case SX_NRW(SDAIPopulationSchema.SchemaInstance)	// extension

		case EI_NEXS
		case EI_NAVL(SDAIParameterDataSchema.ApplicationInstance)
		case EI_NVLD(SDAIParameterDataSchema.EntityInstance)
		case EI_NEXP(SDAIParameterDataSchema.ApplicationInstance)

		case SC_NEXS
		case SC_EXS

		case AI_NEXS
		case AI_NVLD(SDAIParameterDataSchema.AggregateInstance)
		case AI_NSET(SDAIParameterDataSchema.AggregateInstance)

		case VA_NVLD
		case VA_NEXS
		case VA_NSET
		case VT_NVLD

		case IR_NEXS
		case IR_NSET
		case IX_NVLD(SDAIParameterDataSchema.AggregateInstance)

		case ER_NSET
		case OP_NVLD
		case FN_NAVL
		case SY_ERR

		public var errorDescription: SDAIParameterDataSchema.StringValue {
			switch self {
				case .SS_OPN: 	return "Session open"
				case .SS_NAVL:	return "Session not available"
				case .SS_NOPN:	return "Session is not open"

				case .RP_NEXS:	return "Repository does not exist"
				case .RP_NAVL:	return "Repository not available"
				case .RP_OPN: 	return "Repository open"
				case .RP_NOPN:	return "Repository is not open"

				case .TR_EAB: 	return "Transaction ended abnormally"
				case .TR_EXS: 	return "Transaction exists"
				case .TR_NAVL:	return "Transaction currently not available"
				case .TR_RW:  	return "Transaction read-write"
				case .TR_NRW: 	return "Transaction not read-write"
				case .TR_NEXS:	return "Transaction does not exist"

				case .MO_NDEQ:	return "SDAl-model not domain equivalent"
				case .MO_NEXS:	return "SDAI-model does not exist"
				case .MO_NVLD:	return "SDAI-model invalid"
				case .MO_DUP: 	return "SDAI-model duplicate"

				case .MX_NRW: 	return "SDAI-model access not read-write"
				case .MX_NDEF:	return "SDAI-model access not defined"
				case .MX_RW:  	return "SDAI-model access read-write"
				case .MX_RO:  	return "SDAI-model access read-only"

				case .SD_NDEF:	return "Schema definition not defined"

				case .ED_NDEF:	return "Entity definition not defined"
				case .ED_NDEQ:	return "Entity definition not domain equivalent"
				case .ED_NVLD:	return "Entity definition invalid"

				case .RU_NDEF:	return "Rule not defined."

				case .EX_NSUP:	return "Expression evaluation not supported"

				case .AT_NVLD:	return "Attribute invalid"
				case .AT_NDEF:	return "Attribute not defined"

				case .SI_DUP: 	return "Schema instance duplicate"
				case .SI_NEXS:	return "Schema instance does not exist"

				case .SX_NRW: 	return "Schema instance access not read-write"	//extension

				case .EI_NEXS:	return "Entity instance does not exist"
				case .EI_NAVL:	return "Entity instance not available"
				case .EI_NVLD:	return "Entity instance invalid"
				case .EI_NEXP:	return "Entity instance not exported"

				case .SC_NEXS:	return "Scope does not exist"
				case .SC_EXS: 	return "Scope exists"

				case .AI_NEXS:	return "Aggregate instance does not exist"
				case .AI_NVLD:	return "Aggregate instance invalid"
				case .AI_NSET:	return "Aggregate instance is empty"

				case .VA_NVLD:	return "Value invalid"
				case .VA_NEXS:	return "Value does not exist"
				case .VA_NSET:	return "Value not set"
				case .VT_NVLD:	return "Value type invalid"

				case .IR_NEXS:	return "Iterator does not exist"
				case .IR_NSET:	return "Current member is not defined"
				case .IX_NVLD:	return "Index invalid"

				case .ER_NSET:	return "Event recording not set"
				case .OP_NVLD:	return "Operator invalid"
				case .FN_NAVL:	return "Function not available"
				case .SY_ERR: 	return "Underlying system error"
			}
		}//var

		public var errorCode: SDAIParameterDataSchema.IntegerValue {
			switch self {
				case .SS_OPN: 	return 10
				case .SS_NAVL:	return 20
				case .SS_NOPN:	return 30
				case .RP_NEXS:	return 40
				case .RP_NAVL:	return 50
				case .RP_OPN: 	return 60
				case .RP_NOPN:	return 70
				case .TR_EAB: 	return 80
				case .TR_EXS: 	return 90
				case .TR_NAVL:	return 100
				case .TR_RW:  	return 110
				case .TR_NRW: 	return 120
				case .TR_NEXS:	return 130
				case .MO_NDEQ:	return 140
				case .MO_NEXS:	return 150
				case .MO_NVLD:	return 160
				case .MO_DUP: 	return 170
				case .MX_NRW: 	return 180
				case .MX_NDEF:	return 190
				case .MX_RW:  	return 200
				case .MX_RO:  	return 210
				case .SD_NDEF:	return 220
				case .ED_NDEF:	return 230
				case .ED_NDEQ:	return 240
				case .ED_NVLD:	return 250
				case .RU_NDEF:	return 260
				case .EX_NSUP:	return 270
				case .AT_NVLD:	return 280
				case .AT_NDEF:	return 290
				case .SI_DUP: 	return 300
				case .SI_NEXS:	return 310
				case .SX_NRW: 	return 311	//extension
				case .EI_NEXS:	return 320
				case .EI_NAVL:	return 330
				case .EI_NVLD:	return 340
				case .EI_NEXP:	return 350
				case .SC_NEXS:	return 360
				case .SC_EXS: 	return 370
				case .AI_NEXS:	return 380
				case .AI_NVLD:	return 390
				case .AI_NSET:	return 400
				case .VA_NVLD:	return 410
				case .VA_NEXS:	return 420
				case .VA_NSET:	return 430
				case .VT_NVLD:	return 440
				case .IR_NEXS:	return 450
				case .IR_NSET:	return 460
				case .IX_NVLD:	return 470
				case .ER_NSET:	return 480
				case .OP_NVLD:	return 490
				case .FN_NAVL:	return 500
				case .SY_ERR: 	return 1000
			}
		}

		public var errorBase: SDAISessionSchema.ErrorBase? {
			switch self {
				case .SS_OPN(let sdaiSession):
					return .entityInstance(.sdaiSession(sdaiSession))
				case .SS_NAVL:
					return nil
				case .SS_NOPN:
					return nil
				case .RP_NEXS:
					return nil
				case .RP_NAVL(let sdaiRepository):
					return .entityInstance(.sdaiRepository(sdaiRepository))
				case .RP_OPN(let sdaiRepository):
					return .entityInstance(.sdaiRepository(sdaiRepository))
				case .RP_NOPN(let sdaiRepository):
					return .entityInstance(.sdaiRepository(sdaiRepository))
				case .TR_EAB(let sdaiTransaction):
					return .entityInstance(.sdaiTransaction(sdaiTransaction))
				case .TR_EXS(let sdaiTransaction):
					return .entityInstance(.sdaiTransaction(sdaiTransaction))
				case .TR_NAVL(let sdaiTransaction):
					return .entityInstance(.sdaiTransaction(sdaiTransaction))
				case .TR_RW(let sdaiTransaction):
					return .entityInstance(.sdaiTransaction(sdaiTransaction))
				case .TR_NRW(let sdaiTransaction):
					return .entityInstance(.sdaiTransaction(sdaiTransaction))
				case .TR_NEXS:
					return nil
				case .MO_NDEQ(let sdaiModel):
					return .entityInstance(.sdaiModel(sdaiModel))
				case .MO_NEXS:
					return nil
				case .MO_NVLD(let sdaiModel):
					return .entityInstance(.sdaiModel(sdaiModel))
				case .MO_DUP(let sdaiModel):
					return .entityInstance(.sdaiModel(sdaiModel))
				case .MX_NRW(let sdaiModel):
					return .entityInstance(.sdaiModel(sdaiModel))
				case .MX_NDEF(let sdaiModel):
					return .entityInstance(.sdaiModel(sdaiModel))
				case .MX_RW(let sdaiModel):
					return .entityInstance(.sdaiModel(sdaiModel))
				case .MX_RO(let sdaiModel):
					return .entityInstance(.sdaiModel(sdaiModel))
				case .SD_NDEF:
					return nil
				case .ED_NDEF:
					return nil
				case .ED_NDEQ:
					return nil
				case .ED_NVLD(let entityDefinition):
					return .entityInstance(.sdaiEntityDefinition(entityDefinition))
				case .RU_NDEF:
					return nil
				case .EX_NSUP(let bound):
					return .entityInstance(.sdaiBound(bound))
				case .AT_NVLD(let sdaiAttributeType):
					return .entityInstance(.sdaiAttribute(sdaiAttributeType))
				case .AT_NDEF:
					return nil
				case .SI_DUP(let schemaInstance):
					return .entityInstance(.sdaiSchemaInstance(schemaInstance))
				case .SI_NEXS:
					return nil
				case .SX_NRW(let schemaInstance):
					return .entityInstance(.sdaiSchemaInstance(schemaInstance))
				case .EI_NEXS:
					return nil
				case .EI_NAVL(let applicationInstance):
					return .entityInstance(.applicationInstance(applicationInstance))
				case .EI_NVLD(let entityInstance):
					return .entityInstance(entityInstance)
				case .EI_NEXP(let applicationInstance):
					return .entityInstance(.applicationInstance(applicationInstance))
				case .SC_NEXS:
					return nil
				case .SC_EXS:
					return nil
				case .AI_NEXS:
					return nil
				case .AI_NVLD(let aggregateInstance):
					return .aggregateInstance(aggregateInstance)
				case .AI_NSET(let aggregateInstance):
					return .aggregateInstance(aggregateInstance)
				case .VA_NVLD:
					return nil
				case .VA_NEXS:
					return nil
				case .VA_NSET:
					return nil
				case .VT_NVLD:
					return nil
				case .IR_NEXS:
					return nil
				case .IR_NSET:
					return nil
				case .IX_NVLD(let aggregateInstance):
					return .aggregateInstance(aggregateInstance)
				case .ER_NSET:
					return nil
				case .OP_NVLD:
					return nil
				case .FN_NAVL:
					return nil
				case .SY_ERR:
					return nil
			}
		}
	}//enum

}



